/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.auth;

public enum AuthType {
    APIKEY("API_KEY"),
    AES("AES"),
    RSA("RSA");

    private final String type;

    AuthType(final String type) {
        this.type = type;
    }

    public String toString() {
        return type;
    }
}
