/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.locations;

import com.aftership.shipping.base.Resource;

public class LocationsResource extends Resource {
    public static GetLocationsFetcher getLocations() {
        return new GetLocationsFetcher();
    }
}
