/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.http;

import com.aftership.shipping.auth.Auth;
import com.aftership.shipping.auth.AuthType;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.constant.ErrorEnum;
import org.apache.http.client.utils.URIBuilder;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.SimpleDateFormat;
import java.util.*;

public class Request {
    private final Map<String, String> headerParams;
    private final URIBuilder uriBuilder;
    private final HttpMethod method;
    private String body;
    private final String date;

    public Request(HttpMethod method, String path) {
        this.method = method;
        this.date = this.getCurrDate();
        this.uriBuilder = new URIBuilder().setPath(path);
        this.headerParams = new HashMap<>(8);
    }

    public void setDomain(final String domain) throws Exception {
        URIBuilder validateURI = new URIBuilder(domain);
        uriBuilder.setHost(validateURI.getHost());
        uriBuilder.setScheme(validateURI.getScheme());
    }

    public void setAuth(final String apiKey, final String apiSecret, final AuthType authenticationType) throws Exception {
        Auth auth = new Auth(apiKey, apiSecret, authenticationType);
        Map<String, String> authHeaders = auth.getAuthHeader(this);
        if (authHeaders != null) {
            headerParams.putAll(authHeaders);
        }
    }

    public void addQueryParam(final String name, final String value) {
        if (value != null && !value.equals("null")) {
            uriBuilder.addParameter(name, value);
        }
    }

    public void addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name,value);
        }
    }

    private String getCurrDate() {
        SimpleDateFormat sdf3 = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss z", Locale.US);
        sdf3.setTimeZone(TimeZone.getTimeZone("GMT"));
        return sdf3.format(new Date());
    }

    public String getBody() {
        return body;
    }

    public Map<String, String> getHeaders() {
        return headerParams;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getDate() {
        return date;
    }

    public HttpMethod getMethod() {
        return method;
    }

    public URI getURI() throws Exception {
        try {
            return uriBuilder.build();
        } catch (URISyntaxException e) {
            throw new ApiException(ErrorEnum.BAD_REQUEST.name(), e.getMessage());
        }
    }
}
