/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.cancel_labels;

import com.aftership.shipping.base.Resource;

public class CancelLabelsResource extends Resource {
    public static GetCancelLabelsFetcher getCancelLabels() {
        return new GetCancelLabelsFetcher();
    }
    public static PostCancelLabelsCreator postCancelLabels() {
        return new PostCancelLabelsCreator();
    }
    public static GetCancelLabelFetcher getCancelLabel() {
        return new GetCancelLabelFetcher();
    }
}
