/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.cancel_labels;

import com.aftership.shipping.base.Creator;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.PostCancelLabelsResponse;
import com.aftership.shipping.model.PostCancelLabelsResponseData;
import com.aftership.shipping.model.PostCancelLabelsRequest;

public class PostCancelLabelsCreator extends Creator<PostCancelLabelsResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public PostCancelLabelsCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private PostCancelLabelsRequest postCancelLabelsRequest;

    public PostCancelLabelsCreator setPostCancelLabelsRequest(PostCancelLabelsRequest postCancelLabelsRequest) {
        this.postCancelLabelsRequest = postCancelLabelsRequest;
        return this;
    }

    @Override
    public PostCancelLabelsResponse create(AfterShipClient client) throws Exception {
        String path = "/postmen/v3/cancel-labels";
        Request request = new Request(HttpMethod.POST, path);
        request.setBody((new Gson()).toJson(postCancelLabelsRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<PostCancelLabelsResponseData> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<PostCancelLabelsResponseData>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        PostCancelLabelsResponse result = new PostCancelLabelsResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
