/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.constant;

import java.util.HashMap;
import java.util.Map;

public enum ErrorEnum {
    INVALID_API_KEY,
    INVALID_OPTION,
    BAD_REQUEST,
    RATE_LIMIT_EXCEED,
    TIMED_OUT,
    UNKNOWN_ERROR,
    OK,
    UNAUTHORIZED,
    TOO_MANY_REQUESTS,
    INTERNAL_SERVER_ERROR,
    BAD_GATEWAY,
    SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT,
    PENDING,
    INTERNAL_ERROR,
    INTERNAL_ERROR_RETRY,
    INVALID_JSON,
    SHIPPER_ACCOUNT_NOT_FOUND,
    RECORD_NOT_FOUND,
    SHIPPER_ACCOUNT_LOCKED,
    RATE_NOT_FOUND,
    PREPAID_ACCOUNT_DISABLED,
    PAYMENT_CARD_ERROR,
    PAYMENT_API_ERROR,
    PAYMENT_INVALID_REQUEST_AMOUNT_ERROR,
    PAYMENT_INVALID_REQUEST_ERROR,
    OPERATION_NOT_ALLOWED_COURIER,
    TOO_MANY_CUSTOM_REQUESTS,
    RESPONSE_ERROR,
    NO_RESPONSE,
    RATE_REQUEST_FAILED,
    COURIER_ERROR,
    ADDRESS_TOO_LONG,
    ALREADY_CANCELED,
    DOES_NOT_EXIST,
    ALREADY_MANIFESTED,
    NO_SHIPMENTS_MANIFEST,
    NO_AVAILABLE_NUMBER,
    CREDENTIALS_ERROR,
    PAYLOAD_ERROR,
    DUPLICATE_ORDER_NUMBER,
    UNAVAILABLE_SERVICE_TYPE,
    UNAVAILABLE_SERVICE_TYPE_SERVICE_OPTION,
    MAX_WEIGHT;

    private static final Map<Integer, ErrorEnum> META_CODE_MAP = new HashMap<Integer, ErrorEnum>() {
        {
            put(200, OK);
            put(401, UNAUTHORIZED);
            put(429, TOO_MANY_REQUESTS);
            put(500, INTERNAL_SERVER_ERROR);
            put(502, BAD_GATEWAY);
            put(503, SERVICE_UNAVAILABLE);
            put(504, GATEWAY_TIMEOUT);
            put(3001, PENDING);
            put(4100, INTERNAL_ERROR);
            put(4101, INTERNAL_ERROR_RETRY);
            put(4104, BAD_REQUEST);
            put(4109, INVALID_JSON);
            put(4140, SHIPPER_ACCOUNT_NOT_FOUND);
            put(4153, RECORD_NOT_FOUND);
            put(4155, SHIPPER_ACCOUNT_LOCKED);
            put(4157, RATE_NOT_FOUND);
            put(4159, PREPAID_ACCOUNT_DISABLED);
            put(4161, PAYMENT_CARD_ERROR);
            put(4162, PAYMENT_API_ERROR);
            put(4163, PAYMENT_INVALID_REQUEST_AMOUNT_ERROR);
            put(4164, PAYMENT_INVALID_REQUEST_ERROR);
            put(4171, OPERATION_NOT_ALLOWED_COURIER);
            put(4172, TOO_MANY_CUSTOM_REQUESTS);
            put(4703, RESPONSE_ERROR);
            put(4705, NO_RESPONSE);
            put(4713, RATE_REQUEST_FAILED);
            put(4715, COURIER_ERROR);
            put(4716, ADDRESS_TOO_LONG);
            put(4722, ALREADY_CANCELED);
            put(4723, DOES_NOT_EXIST);
            put(4724, ALREADY_MANIFESTED);
            put(4725, NO_SHIPMENTS_MANIFEST);
            put(4730, NO_AVAILABLE_NUMBER);
            put(4732, CREDENTIALS_ERROR);
            put(4733, PAYLOAD_ERROR);
            put(4801, DUPLICATE_ORDER_NUMBER);
            put(4802, UNAVAILABLE_SERVICE_TYPE);
            put(4803, UNAVAILABLE_SERVICE_TYPE_SERVICE_OPTION);
            put(4804, MAX_WEIGHT);
        }
    };

    public static String getCode(int statusCode, int metaCode) {
        ErrorEnum e = META_CODE_MAP.get(metaCode);
        if (e != null) {
            return e.name();
        }

        if (statusCode >= 400 && statusCode < 500) {
            return ErrorEnum.BAD_REQUEST.name();
        }

        return ErrorEnum.UNKNOWN_ERROR.name();
    }
}