/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.address_validations_beta;

import com.aftership.shipping.base.Resource;

public class AddressValidationsBetaResource extends Resource {
    public static PostAddressValidationsCreator postAddressValidations() {
        return new PostAddressValidationsCreator();
    }
}
