/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.address_validations_beta;

import com.aftership.shipping.base.Creator;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.PostAddressValidationsResponse;
import com.aftership.shipping.model.AddressValidationV3;
import com.aftership.shipping.model.PostAddressValidationsRequest;

public class PostAddressValidationsCreator extends Creator<PostAddressValidationsResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public PostAddressValidationsCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private PostAddressValidationsRequest postAddressValidationsRequest;

    public PostAddressValidationsCreator setPostAddressValidationsRequest(PostAddressValidationsRequest postAddressValidationsRequest) {
        this.postAddressValidationsRequest = postAddressValidationsRequest;
        return this;
    }

    @Override
    public PostAddressValidationsResponse create(AfterShipClient client) throws Exception {
        String path = "/postmen/v3/address-validations";
        Request request = new Request(HttpMethod.POST, path);
        request.setBody((new Gson()).toJson(postAddressValidationsRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<AddressValidationV3> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<AddressValidationV3>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        PostAddressValidationsResponse result = new PostAddressValidationsResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
