/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.labels;

import com.aftership.shipping.base.Fetcher;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.GetLabelResponse;
import com.aftership.shipping.model.LabelV3;

public class GetLabelFetcher extends Fetcher<GetLabelResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public GetLabelFetcher addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private String id;


    public GetLabelFetcher setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public GetLabelResponse fetch(AfterShipClient client) throws Exception {
        if (id == null || id.isEmpty()) {
            throw new ApiException(ErrorEnum.BAD_REQUEST.name(), "Invalid request: `id` is invalid");
        }
        String path = String.format("/postmen/v3/labels/%s", id);
        Request request = new Request(HttpMethod.GET, path);
        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<LabelV3> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<LabelV3>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        GetLabelResponse result = new GetLabelResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
