/*
 * @Author: Yee zy.liu@aftership.com
 * @Date: 2025-09-30 14:03:04
 * @LastEditors: Yee zy.liu@aftership.com
 * @LastEditTime: 2025-09-30 14:26:23
 * @FilePath: /shipping-sdk-java/src/main/java/com/aftership/shipping/labels/PostLabelsCreator.java
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.labels;

import com.aftership.shipping.base.Creator;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.PostLabelsResponse;
import com.aftership.shipping.model.LabelV3;
import com.aftership.shipping.model.PostLabelsRequest;

public class PostLabelsCreator extends Creator<PostLabelsResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public PostLabelsCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private PostLabelsRequest postLabelsRequest;

    public PostLabelsCreator setPostLabelsRequest(PostLabelsRequest postLabelsRequest) {
        this.postLabelsRequest = postLabelsRequest;
        return this;
    }

    @Override
    public PostLabelsResponse create(AfterShipClient client) throws Exception {
      System.err.println("PostLabelsCreator create =========================>");  
			String path = "/postmen/v3/labels";
        Request request = new Request(HttpMethod.POST, path);
        request.setBody((new Gson()).toJson(postLabelsRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<LabelV3> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<LabelV3>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        PostLabelsResponse result = new PostLabelsResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
