/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.manifests;

import com.aftership.shipping.base.Resource;

public class ManifestsResource extends Resource {
    public static GetManifestsFetcher getManifests() {
        return new GetManifestsFetcher();
    }
    public static PostManifestsCreator postManifests() {
        return new PostManifestsCreator();
    }
    public static GetManifestFetcher getManifest() {
        return new GetManifestFetcher();
    }
}
