/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class AddressV3Location extends Resource {

    @SerializedName("lat")
    private Float lat;

    @SerializedName("lng")
    private Float lng;

    public  Float getLat() {
        return lat;
    }

    public void setLat( Float lat) {
        this.lat = lat;
    }

    public  Float getLng() {
        return lng;
    }

    public void setLng( Float lng) {
        this.lng = lng;
    }

}
