/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum AddressV3TaxIdType {
    @SerializedName("vat")
    Vat("vat"),

    @SerializedName("gst")
    Gst("gst"),

    @SerializedName("eori")
    Eori("eori"),

    @SerializedName("ioss")
    Ioss("ioss"),

    @SerializedName("pan")
    Pan("pan"),

    @SerializedName("other")
    Other("other");

    private final String value;

    AddressV3TaxIdType(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
