/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum AddressValidationV3Status {
    @SerializedName("valid")
    Valid("valid"),

    @SerializedName("invalid")
    Invalid("invalid");

    private final String value;

    AddressValidationV3Status(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
