/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum BillingV3PaidBy {
    @SerializedName("shipper")
    Shipper("shipper"),

    @SerializedName("third_party")
    ThirdParty("third_party"),

    @SerializedName("recipient")
    Recipient("recipient");

    private final String value;

    BillingV3PaidBy(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
