/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class BillingV3 extends Resource {

    @SerializedName("paid_by")
    private BillingV3PaidBy paidBy;

    @SerializedName("method")
    private PaymentMethodAccountV3 method;

    public  BillingV3PaidBy getPaidBy() {
        return paidBy;
    }

    public void setPaidBy( BillingV3PaidBy paidBy) {
        this.paidBy = paidBy;
    }

    public  PaymentMethodAccountV3 getMethod() {
        return method;
    }

    public void setMethod( PaymentMethodAccountV3 method) {
        this.method = method;
    }

}
