/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class CourierV3CourierBoxTypes extends Resource {

    @SerializedName("box_name")
    private String boxName;

    @SerializedName("box_type")
    private String boxType;

    public  String getBoxName() {
        return boxName;
    }

    public void setBoxName( String boxName) {
        this.boxName = boxName;
    }

    public  String getBoxType() {
        return boxType;
    }

    public void setBoxType( String boxType) {
        this.boxType = boxType;
    }

}
