/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class CourierV3 extends Resource {

    @SerializedName("slug")
    private String slug;

    @SerializedName("name")
    private String name;

    @SerializedName("operations")
    private CourierV3Operations operations;

    @SerializedName("ship_from")
    private String shipFrom;

    @SerializedName("ship_to")
    private String shipTo;

    @SerializedName("paper_sizes")
    private java.util.List<String> paperSizes;

    @SerializedName("courier_service_types")
    private java.util.List<CourierV3CourierServiceTypes> courierServiceTypes;

    @SerializedName("courier_box_types")
    private java.util.List<CourierV3CourierBoxTypes> courierBoxTypes;

    public  String getSlug() {
        return slug;
    }

    public void setSlug( String slug) {
        this.slug = slug;
    }

    public  String getName() {
        return name;
    }

    public void setName( String name) {
        this.name = name;
    }

    public  CourierV3Operations getOperations() {
        return operations;
    }

    public void setOperations( CourierV3Operations operations) {
        this.operations = operations;
    }

    public  String getShipFrom() {
        return shipFrom;
    }

    public void setShipFrom( String shipFrom) {
        this.shipFrom = shipFrom;
    }

    public  String getShipTo() {
        return shipTo;
    }

    public void setShipTo( String shipTo) {
        this.shipTo = shipTo;
    }

    public java.util.List<String>  getPaperSizes() {
        return paperSizes;
    }

    public void setPaperSizes(java.util.List<String>  paperSizes) {
        this.paperSizes = paperSizes;
    }

    public java.util.List<CourierV3CourierServiceTypes>  getCourierServiceTypes() {
        return courierServiceTypes;
    }

    public void setCourierServiceTypes(java.util.List<CourierV3CourierServiceTypes>  courierServiceTypes) {
        this.courierServiceTypes = courierServiceTypes;
    }

    public java.util.List<CourierV3CourierBoxTypes>  getCourierBoxTypes() {
        return courierBoxTypes;
    }

    public void setCourierBoxTypes(java.util.List<CourierV3CourierBoxTypes>  courierBoxTypes) {
        this.courierBoxTypes = courierBoxTypes;
    }

}
