/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class CustomsV3 extends Resource {

    @SerializedName("purpose")
    private CustomsV3Purpose purpose;

    @SerializedName("terms_of_trade")
    private CustomsV3TermsOfTrade termsOfTrade;

    @SerializedName("eei")
    private Object eei;

    @SerializedName("billing")
    private BillingV3 billing;

    @SerializedName("importer_address")
    private AddressV3 importerAddress;

    @SerializedName("broker_address")
    private AddressV3 brokerAddress;

    @SerializedName("passport")
    private CustomsV3Passport passport;

    @SerializedName("additional_charges")
    private java.util.List<CustomsV3AdditionalCharges> additionalCharges;

    public  CustomsV3Purpose getPurpose() {
        return purpose;
    }

    public void setPurpose( CustomsV3Purpose purpose) {
        this.purpose = purpose;
    }

    public  CustomsV3TermsOfTrade getTermsOfTrade() {
        return termsOfTrade;
    }

    public void setTermsOfTrade( CustomsV3TermsOfTrade termsOfTrade) {
        this.termsOfTrade = termsOfTrade;
    }

    public  Object getEei() {
        return eei;
    }

    public void setEei( Object eei) {
        this.eei = eei;
    }

    public  BillingV3 getBilling() {
        return billing;
    }

    public void setBilling( BillingV3 billing) {
        this.billing = billing;
    }

    public  AddressV3 getImporterAddress() {
        return importerAddress;
    }

    public void setImporterAddress( AddressV3 importerAddress) {
        this.importerAddress = importerAddress;
    }

    public  AddressV3 getBrokerAddress() {
        return brokerAddress;
    }

    public void setBrokerAddress( AddressV3 brokerAddress) {
        this.brokerAddress = brokerAddress;
    }

    public  CustomsV3Passport getPassport() {
        return passport;
    }

    public void setPassport( CustomsV3Passport passport) {
        this.passport = passport;
    }

    public java.util.List<CustomsV3AdditionalCharges>  getAdditionalCharges() {
        return additionalCharges;
    }

    public void setAdditionalCharges(java.util.List<CustomsV3AdditionalCharges>  additionalCharges) {
        this.additionalCharges = additionalCharges;
    }

}
