/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum CustomsV3Purpose {
    @SerializedName("gift")
    Gift("gift"),

    @SerializedName("merchandise")
    Merchandise("merchandise"),

    @SerializedName("personal")
    Personal("personal"),

    @SerializedName("sample")
    Sample("sample"),

    @SerializedName("return")
    Return("return"),

    @SerializedName("repair")
    Repair("repair"),

    @SerializedName("non-merchandise")
    NonMerchandise("non-merchandise");

    private final String value;

    CustomsV3Purpose(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
