/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum CustomsV3AdditionalChargesType {
    @SerializedName("insurance")
    Insurance("insurance"),

    @SerializedName("freight")
    Freight("freight"),

    @SerializedName("other")
    Other("other");

    private final String value;

    CustomsV3AdditionalChargesType(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
