/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum CustomsV3TermsOfTrade {
    @SerializedName("dat")
    Dat("dat"),

    @SerializedName("ddu")
    Ddu("ddu"),

    @SerializedName("ddp")
    Ddp("ddp"),

    @SerializedName("dap")
    Dap("dap"),

    @SerializedName("exw")
    Exw("exw"),

    @SerializedName("fca")
    Fca("fca"),

    @SerializedName("fob")
    Fob("fob"),

    @SerializedName("cip")
    Cip("cip"),

    @SerializedName("cif")
    Cif("cif"),

    @SerializedName("cpt")
    Cpt("cpt"),

    @SerializedName("cfr")
    Cfr("cfr"),

    @SerializedName("dpu")
    Dpu("dpu");

    private final String value;

    CustomsV3TermsOfTrade(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
