/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class CustomsV3Passport extends Resource {

    @SerializedName("number")
    private String number;

    @SerializedName("issue_date")
    private String issueDate;

    public  String getNumber() {
        return number;
    }

    public void setNumber( String number) {
        this.number = number;
    }

    public  String getIssueDate() {
        return issueDate;
    }

    public void setIssueDate( String issueDate) {
        this.issueDate = issueDate;
    }

}
