/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class ErrorV3 extends Resource {

    @SerializedName("path")
    private String path;

    @SerializedName("info")
    private String info;

    public  String getPath() {
        return path;
    }

    public void setPath( String path) {
        this.path = path;
    }

    public  String getInfo() {
        return info;
    }

    public void setInfo( String info) {
        this.info = info;
    }

}
