/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class FilesV3Label extends Resource {

    @SerializedName("paper_size")
    private FilesV3LabelPaperSize paperSize;

    @SerializedName("url")
    private String url;

    @SerializedName("file_type")
    private FilesV3LabelFileType fileType;

    public  FilesV3LabelPaperSize getPaperSize() {
        return paperSize;
    }

    public void setPaperSize( FilesV3LabelPaperSize paperSize) {
        this.paperSize = paperSize;
    }

    public  String getUrl() {
        return url;
    }

    public void setUrl( String url) {
        this.url = url;
    }

    public  FilesV3LabelFileType getFileType() {
        return fileType;
    }

    public void setFileType( FilesV3LabelFileType fileType) {
        this.fileType = fileType;
    }

}
