/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum FilesV3LabelPaperSize {
    @SerializedName("3x5")
    _3x5("3x5"),

    @SerializedName("4x4")
    _4x4("4x4"),

    @SerializedName("4x5")
    _4x5("4x5"),

    @SerializedName("4x6")
    _4x6("4x6"),

    @SerializedName("4x6.75")
    _4x6_75("4x6.75"),

    @SerializedName("4x7")
    _4x7("4x7"),

    @SerializedName("4x8")
    _4x8("4x8"),

    @SerializedName("a4")
    A4("a4"),

    @SerializedName("a5")
    A5("a5"),

    @SerializedName("default")
    Default("default"),

    @SerializedName("8.5x6.3")
    _8_5x6_3("8.5x6.3");

    private final String value;

    FilesV3LabelPaperSize(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
