/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;
import java.util.List;
import java.util.Map;

public class GetCancelPickupResponse extends Resource {

    private java.util.Map<String, java.util.List<String>> responseHeader;

    private CancelPickupV3 data;

    public java.util.Map<String, java.util.List<String>> getResponseHeader() {
        return responseHeader;
    }

    public void setResponseHeader(java.util.Map<String, java.util.List<String>> responseHeader) {
        this.responseHeader = responseHeader;
    }

    public CancelPickupV3 getData() {
        return data;
    }

    public void setData(CancelPickupV3 data) {
        this.data = data;
    }
}
