/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class GetCouriersResponseData extends Resource {

    @SerializedName("couriers")
    private java.util.List<CourierV3> couriers;

    public java.util.List<CourierV3>  getCouriers() {
        return couriers;
    }

    public void setCouriers(java.util.List<CourierV3>  couriers) {
        this.couriers = couriers;
    }

}
