/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class GetLabelsResponseData extends Resource {

    @SerializedName("next_token")
    private String nextToken;

    @SerializedName("limit")
    private Integer limit;

    @SerializedName("created_at_min")
    private String createdAtMin;

    @SerializedName("created_at_max")
    private String createdAtMax;

    @SerializedName("labels")
    private java.util.List<LabelV3> labels;

    public  String getNextToken() {
        return nextToken;
    }

    public void setNextToken( String nextToken) {
        this.nextToken = nextToken;
    }

    public  Integer getLimit() {
        return limit;
    }

    public void setLimit( Integer limit) {
        this.limit = limit;
    }

    public  String getCreatedAtMin() {
        return createdAtMin;
    }

    public void setCreatedAtMin( String createdAtMin) {
        this.createdAtMin = createdAtMin;
    }

    public  String getCreatedAtMax() {
        return createdAtMax;
    }

    public void setCreatedAtMax( String createdAtMax) {
        this.createdAtMax = createdAtMax;
    }

    public java.util.List<LabelV3>  getLabels() {
        return labels;
    }

    public void setLabels(java.util.List<LabelV3>  labels) {
        this.labels = labels;
    }

}
