/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class GetLocationsResponseData extends Resource {

    @SerializedName("locations")
    private java.util.List<LocationV3> locations;

    @SerializedName("drop_off_link")
    private String dropOffLink;

    public java.util.List<LocationV3>  getLocations() {
        return locations;
    }

    public void setLocations(java.util.List<LocationV3>  locations) {
        this.locations = locations;
    }

    public  String getDropOffLink() {
        return dropOffLink;
    }

    public void setDropOffLink( String dropOffLink) {
        this.dropOffLink = dropOffLink;
    }

}
