/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;
import java.util.List;
import java.util.Map;

public class GetPickupsResponse extends Resource {

    private java.util.Map<String, java.util.List<String>> responseHeader;

    private GetPickupsResponseData data;

    public java.util.Map<String, java.util.List<String>> getResponseHeader() {
        return responseHeader;
    }

    public void setResponseHeader(java.util.Map<String, java.util.List<String>> responseHeader) {
        this.responseHeader = responseHeader;
    }

    public GetPickupsResponseData getData() {
        return data;
    }

    public void setData(GetPickupsResponseData data) {
        this.data = data;
    }
}
