/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class InputFilesV3CustomsDeclaration extends Resource {

    @SerializedName("content")
    private String content;

    public  String getContent() {
        return content;
    }

    public void setContent( String content) {
        this.content = content;
    }

}
