/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum InvoiceV3Type {
    @SerializedName("commercial")
    Commercial("commercial"),

    @SerializedName("proforma")
    Proforma("proforma");

    private final String value;

    InvoiceV3Type(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
