/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class ItemV3 extends Resource {

    @SerializedName("quantity")
    private Integer quantity;

    @SerializedName("description")
    private String description;

    @SerializedName("description_cn")
    private String descriptionCn;

    @SerializedName("price")
    private MoneyV3 price;

    @SerializedName("item_id")
    private String itemId;

    @SerializedName("origin_country")
    private String originCountry;

    @SerializedName("weight")
    private WeightV3 weight;

    @SerializedName("sku")
    private String sku;

    @SerializedName("hs_code")
    private String hsCode;

    @SerializedName("outbound_hs_code")
    private String outboundHsCode;

    @SerializedName("return_reason")
    private String returnReason;

    @SerializedName("dimension")
    private DimensionV3 dimension;

    @SerializedName("barcode")
    private String barcode;

    public  Integer getQuantity() {
        return quantity;
    }

    public void setQuantity( Integer quantity) {
        this.quantity = quantity;
    }

    public  String getDescription() {
        return description;
    }

    public void setDescription( String description) {
        this.description = description;
    }

    public  String getDescriptionCn() {
        return descriptionCn;
    }

    public void setDescriptionCn( String descriptionCn) {
        this.descriptionCn = descriptionCn;
    }

    public  MoneyV3 getPrice() {
        return price;
    }

    public void setPrice( MoneyV3 price) {
        this.price = price;
    }

    public  String getItemId() {
        return itemId;
    }

    public void setItemId( String itemId) {
        this.itemId = itemId;
    }

    public  String getOriginCountry() {
        return originCountry;
    }

    public void setOriginCountry( String originCountry) {
        this.originCountry = originCountry;
    }

    public  WeightV3 getWeight() {
        return weight;
    }

    public void setWeight( WeightV3 weight) {
        this.weight = weight;
    }

    public  String getSku() {
        return sku;
    }

    public void setSku( String sku) {
        this.sku = sku;
    }

    public  String getHsCode() {
        return hsCode;
    }

    public void setHsCode( String hsCode) {
        this.hsCode = hsCode;
    }

    public  String getOutboundHsCode() {
        return outboundHsCode;
    }

    public void setOutboundHsCode( String outboundHsCode) {
        this.outboundHsCode = outboundHsCode;
    }

    public  String getReturnReason() {
        return returnReason;
    }

    public void setReturnReason( String returnReason) {
        this.returnReason = returnReason;
    }

    public  DimensionV3 getDimension() {
        return dimension;
    }

    public void setDimension( DimensionV3 dimension) {
        this.dimension = dimension;
    }

    public  String getBarcode() {
        return barcode;
    }

    public void setBarcode( String barcode) {
        this.barcode = barcode;
    }

}
