/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class LabelV3CarrierReferences extends Resource {

    @SerializedName("pickup_reference")
    private String pickupReference;

    @SerializedName("pickup_location_code")
    private String pickupLocationCode;

    public  String getPickupReference() {
        return pickupReference;
    }

    public void setPickupReference( String pickupReference) {
        this.pickupReference = pickupReference;
    }

    public  String getPickupLocationCode() {
        return pickupLocationCode;
    }

    public void setPickupLocationCode( String pickupLocationCode) {
        this.pickupLocationCode = pickupLocationCode;
    }

}
