/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class LabelV3 extends Resource {

    @SerializedName("id")
    private String id;

    @SerializedName("status")
    private LabelV3Status status;

    @SerializedName("ship_date")
    private String shipDate;

    @SerializedName("tracking_numbers")
    private java.util.List<String> trackingNumbers;

    @SerializedName("carrier_references")
    private java.util.List<LabelV3CarrierReferences> carrierReferences;

    @SerializedName("files")
    private FilesV3 files;

    @SerializedName("rate")
    private RateV3 rate;

    @SerializedName("created_at")
    private String createdAt;

    @SerializedName("updated_at")
    private String updatedAt;

    @SerializedName("references")
    private java.util.List<String> references;

    @SerializedName("shipper_account")
    private ReferenceV3 shipperAccount;

    @SerializedName("service_type")
    private String serviceType;

    @SerializedName("order_number")
    private String orderNumber;

    @SerializedName("service_options")
    private java.util.List<Object> serviceOptions;

    @SerializedName("order_id")
    private String orderId;

    @SerializedName("custom_fields")
    private java.util.Map<String,String> customFields;

    @SerializedName("carrier_redirect_link")
    private String carrierRedirectLink;

    public  String getId() {
        return id;
    }

    public void setId( String id) {
        this.id = id;
    }

    public  LabelV3Status getStatus() {
        return status;
    }

    public void setStatus( LabelV3Status status) {
        this.status = status;
    }

    public  String getShipDate() {
        return shipDate;
    }

    public void setShipDate( String shipDate) {
        this.shipDate = shipDate;
    }

    public java.util.List<String>  getTrackingNumbers() {
        return trackingNumbers;
    }

    public void setTrackingNumbers(java.util.List<String>  trackingNumbers) {
        this.trackingNumbers = trackingNumbers;
    }

    public java.util.List<LabelV3CarrierReferences>  getCarrierReferences() {
        return carrierReferences;
    }

    public void setCarrierReferences(java.util.List<LabelV3CarrierReferences>  carrierReferences) {
        this.carrierReferences = carrierReferences;
    }

    public  FilesV3 getFiles() {
        return files;
    }

    public void setFiles( FilesV3 files) {
        this.files = files;
    }

    public  RateV3 getRate() {
        return rate;
    }

    public void setRate( RateV3 rate) {
        this.rate = rate;
    }

    public  String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt( String createdAt) {
        this.createdAt = createdAt;
    }

    public  String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt( String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public java.util.List<String>  getReferences() {
        return references;
    }

    public void setReferences(java.util.List<String>  references) {
        this.references = references;
    }

    public  ReferenceV3 getShipperAccount() {
        return shipperAccount;
    }

    public void setShipperAccount( ReferenceV3 shipperAccount) {
        this.shipperAccount = shipperAccount;
    }

    public  String getServiceType() {
        return serviceType;
    }

    public void setServiceType( String serviceType) {
        this.serviceType = serviceType;
    }

    public  String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber( String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public java.util.List<Object>  getServiceOptions() {
        return serviceOptions;
    }

    public void setServiceOptions(java.util.List<Object>  serviceOptions) {
        this.serviceOptions = serviceOptions;
    }

    public  String getOrderId() {
        return orderId;
    }

    public void setOrderId( String orderId) {
        this.orderId = orderId;
    }

    public  java.util.Map<String,String> getCustomFields() {
        return customFields;
    }

    public void setCustomFields( java.util.Map<String,String> customFields) {
        this.customFields = customFields;
    }

    public  String getCarrierRedirectLink() {
        return carrierRedirectLink;
    }

    public void setCarrierRedirectLink( String carrierRedirectLink) {
        this.carrierRedirectLink = carrierRedirectLink;
    }

}
