/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class LocationV3Address extends Resource {

    @SerializedName("street")
    private String street;

    @SerializedName("postal_code")
    private String postalCode;

    @SerializedName("city")
    private String city;

    @SerializedName("state")
    private String state;

    @SerializedName("country")
    private String country;

    @SerializedName("latitude")
    private Float latitude;

    @SerializedName("longitude")
    private Float longitude;

    public  String getStreet() {
        return street;
    }

    public void setStreet( String street) {
        this.street = street;
    }

    public  String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode( String postalCode) {
        this.postalCode = postalCode;
    }

    public  String getCity() {
        return city;
    }

    public void setCity( String city) {
        this.city = city;
    }

    public  String getState() {
        return state;
    }

    public void setState( String state) {
        this.state = state;
    }

    public  String getCountry() {
        return country;
    }

    public void setCountry( String country) {
        this.country = country;
    }

    public  Float getLatitude() {
        return latitude;
    }

    public void setLatitude( Float latitude) {
        this.latitude = latitude;
    }

    public  Float getLongitude() {
        return longitude;
    }

    public void setLongitude( Float longitude) {
        this.longitude = longitude;
    }

}
