/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class LocationV3 extends Resource {

    @SerializedName("location_id")
    private String locationId;

    @SerializedName("name")
    private String name;

    @SerializedName("distance")
    private Float distance;

    @SerializedName("distance_unit")
    private LocationV3DistanceUnit distanceUnit;

    @SerializedName("phone")
    private String phone;

    @SerializedName("services")
    private java.util.List<String> services;

    @SerializedName("address")
    private LocationV3Address address;

    @SerializedName("business_hours")
    private java.util.List<LocationV3BusinessHours> businessHours;

    @SerializedName("instructions")
    private String instructions;

    @SerializedName("location_type")
    private String locationType;

    @SerializedName("business_classification")
    private String businessClassification;

    public  String getLocationId() {
        return locationId;
    }

    public void setLocationId( String locationId) {
        this.locationId = locationId;
    }

    public  String getName() {
        return name;
    }

    public void setName( String name) {
        this.name = name;
    }

    public  Float getDistance() {
        return distance;
    }

    public void setDistance( Float distance) {
        this.distance = distance;
    }

    public  LocationV3DistanceUnit getDistanceUnit() {
        return distanceUnit;
    }

    public void setDistanceUnit( LocationV3DistanceUnit distanceUnit) {
        this.distanceUnit = distanceUnit;
    }

    public  String getPhone() {
        return phone;
    }

    public void setPhone( String phone) {
        this.phone = phone;
    }

    public java.util.List<String>  getServices() {
        return services;
    }

    public void setServices(java.util.List<String>  services) {
        this.services = services;
    }

    public  LocationV3Address getAddress() {
        return address;
    }

    public void setAddress( LocationV3Address address) {
        this.address = address;
    }

    public java.util.List<LocationV3BusinessHours>  getBusinessHours() {
        return businessHours;
    }

    public void setBusinessHours(java.util.List<LocationV3BusinessHours>  businessHours) {
        this.businessHours = businessHours;
    }

    public  String getInstructions() {
        return instructions;
    }

    public void setInstructions( String instructions) {
        this.instructions = instructions;
    }

    public  String getLocationType() {
        return locationType;
    }

    public void setLocationType( String locationType) {
        this.locationType = locationType;
    }

    public  String getBusinessClassification() {
        return businessClassification;
    }

    public void setBusinessClassification( String businessClassification) {
        this.businessClassification = businessClassification;
    }

}
