/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum LocationV3DistanceUnit {
    @SerializedName("km")
    Km("km"),

    @SerializedName("mi")
    Mi("mi");

    private final String value;

    LocationV3DistanceUnit(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
