/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class ManifestV3Labels extends Resource {

    @SerializedName("id")
    private String id;

    @SerializedName("manifested")
    private Boolean manifested;

    public  String getId() {
        return id;
    }

    public void setId( String id) {
        this.id = id;
    }

    public  Boolean getManifested() {
        return manifested;
    }

    public void setManifested( Boolean manifested) {
        this.manifested = manifested;
    }

}
