/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class MetaV3 extends Resource {

    @SerializedName("code")
    private Integer code;

    @SerializedName("message")
    private String message;

    @SerializedName("details")
    private java.util.List<ErrorV3> details;

    @SerializedName("retryable")
    private Boolean retryable;

    public  Integer getCode() {
        return code;
    }

    public void setCode( Integer code) {
        this.code = code;
    }

    public  String getMessage() {
        return message;
    }

    public void setMessage( String message) {
        this.message = message;
    }

    public java.util.List<ErrorV3>  getDetails() {
        return details;
    }

    public void setDetails(java.util.List<ErrorV3>  details) {
        this.details = details;
    }

    public  Boolean getRetryable() {
        return retryable;
    }

    public void setRetryable( Boolean retryable) {
        this.retryable = retryable;
    }

}
