/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class MoneyV3 extends Resource {

    @SerializedName("currency")
    private MoneyV3Currency currency;

    @SerializedName("amount")
    private Float amount;

    public  MoneyV3Currency getCurrency() {
        return currency;
    }

    public void setCurrency( MoneyV3Currency currency) {
        this.currency = currency;
    }

    public  Float getAmount() {
        return amount;
    }

    public void setAmount( Float amount) {
        this.amount = amount;
    }

}
