/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum NoEeiV3FtrExemption {
    @SerializedName("noeei_30_37_a")
    Noeei3037A("noeei_30_37_a"),

    @SerializedName("noeei_30_37_h")
    Noeei3037H("noeei_30_37_h"),

    @SerializedName("noeei_30_36")
    Noeei3036("noeei_30_36");

    private final String value;

    NoEeiV3FtrExemption(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
