/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class NoEeiV3 extends Resource {

    @SerializedName("type")
    private String type;

    @SerializedName("ftr_exemption")
    private NoEeiV3FtrExemption ftrExemption;

    public  String getType() {
        return type;
    }

    public void setType( String type) {
        this.type = type;
    }

    public  NoEeiV3FtrExemption getFtrExemption() {
        return ftrExemption;
    }

    public void setFtrExemption( NoEeiV3FtrExemption ftrExemption) {
        this.ftrExemption = ftrExemption;
    }

}
