/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class ParcelV3 extends Resource {

    @SerializedName("box_type")
    private String boxType;

    @SerializedName("dimension")
    private DimensionV3 dimension;

    @SerializedName("items")
    private java.util.List<ItemV3> items;

    @SerializedName("description")
    private String description;

    @SerializedName("weight")
    private WeightV3 weight;

    public  String getBoxType() {
        return boxType;
    }

    public void setBoxType( String boxType) {
        this.boxType = boxType;
    }

    public  DimensionV3 getDimension() {
        return dimension;
    }

    public void setDimension( DimensionV3 dimension) {
        this.dimension = dimension;
    }

    public java.util.List<ItemV3>  getItems() {
        return items;
    }

    public void setItems(java.util.List<ItemV3>  items) {
        this.items = items;
    }

    public  String getDescription() {
        return description;
    }

    public void setDescription( String description) {
        this.description = description;
    }

    public  WeightV3 getWeight() {
        return weight;
    }

    public void setWeight( WeightV3 weight) {
        this.weight = weight;
    }

}
