/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum PaymentMethodAccountV3Country {
    @SerializedName("ABW")
    Abw("ABW"),

    @SerializedName("AFG")
    Afg("AFG"),

    @SerializedName("AGO")
    Ago("AGO"),

    @SerializedName("AIA")
    Aia("AIA"),

    @SerializedName("ALA")
    Ala("ALA"),

    @SerializedName("ALB")
    Alb("ALB"),

    @SerializedName("AND")
    And("AND"),

    @SerializedName("ANT")
    Ant("ANT"),

    @SerializedName("ARE")
    Are("ARE"),

    @SerializedName("ARG")
    Arg("ARG"),

    @SerializedName("ARM")
    Arm("ARM"),

    @SerializedName("ASM")
    Asm("ASM"),

    @SerializedName("ATA")
    Ata("ATA"),

    @SerializedName("ATF")
    Atf("ATF"),

    @SerializedName("ATG")
    Atg("ATG"),

    @SerializedName("AUS")
    Aus("AUS"),

    @SerializedName("AUT")
    Aut("AUT"),

    @SerializedName("AZE")
    Aze("AZE"),

    @SerializedName("BDI")
    Bdi("BDI"),

    @SerializedName("BEL")
    Bel("BEL"),

    @SerializedName("BEN")
    Ben("BEN"),

    @SerializedName("BES")
    Bes("BES"),

    @SerializedName("BFA")
    Bfa("BFA"),

    @SerializedName("BGD")
    Bgd("BGD"),

    @SerializedName("BGR")
    Bgr("BGR"),

    @SerializedName("BHR")
    Bhr("BHR"),

    @SerializedName("BHS")
    Bhs("BHS"),

    @SerializedName("BIH")
    Bih("BIH"),

    @SerializedName("BLM")
    Blm("BLM"),

    @SerializedName("BLR")
    Blr("BLR"),

    @SerializedName("BLZ")
    Blz("BLZ"),

    @SerializedName("BMU")
    Bmu("BMU"),

    @SerializedName("BOL")
    Bol("BOL"),

    @SerializedName("BRA")
    Bra("BRA"),

    @SerializedName("BRB")
    Brb("BRB"),

    @SerializedName("BRN")
    Brn("BRN"),

    @SerializedName("BTN")
    Btn("BTN"),

    @SerializedName("BVT")
    Bvt("BVT"),

    @SerializedName("BWA")
    Bwa("BWA"),

    @SerializedName("CAF")
    Caf("CAF"),

    @SerializedName("CAN")
    Can("CAN"),

    @SerializedName("CCK")
    Cck("CCK"),

    @SerializedName("CHE")
    Che("CHE"),

    @SerializedName("CHL")
    Chl("CHL"),

    @SerializedName("CHN")
    Chn("CHN"),

    @SerializedName("CIV")
    Civ("CIV"),

    @SerializedName("CMR")
    Cmr("CMR"),

    @SerializedName("COD")
    Cod("COD"),

    @SerializedName("COG")
    Cog("COG"),

    @SerializedName("COK")
    Cok("COK"),

    @SerializedName("COL")
    Col("COL"),

    @SerializedName("COM")
    Com("COM"),

    @SerializedName("CPV")
    Cpv("CPV"),

    @SerializedName("CRI")
    Cri("CRI"),

    @SerializedName("CUB")
    Cub("CUB"),

    @SerializedName("CUW")
    Cuw("CUW"),

    @SerializedName("CXR")
    Cxr("CXR"),

    @SerializedName("CYM")
    Cym("CYM"),

    @SerializedName("CYP")
    Cyp("CYP"),

    @SerializedName("CZE")
    Cze("CZE"),

    @SerializedName("DEU")
    Deu("DEU"),

    @SerializedName("DJI")
    Dji("DJI"),

    @SerializedName("DMA")
    Dma("DMA"),

    @SerializedName("DNK")
    Dnk("DNK"),

    @SerializedName("DOM")
    Dom("DOM"),

    @SerializedName("DZA")
    Dza("DZA"),

    @SerializedName("ECU")
    Ecu("ECU"),

    @SerializedName("EGY")
    Egy("EGY"),

    @SerializedName("ERI")
    Eri("ERI"),

    @SerializedName("ESH")
    Esh("ESH"),

    @SerializedName("ESP")
    Esp("ESP"),

    @SerializedName("EST")
    Est("EST"),

    @SerializedName("ETH")
    Eth("ETH"),

    @SerializedName("FIN")
    Fin("FIN"),

    @SerializedName("FJI")
    Fji("FJI"),

    @SerializedName("FLK")
    Flk("FLK"),

    @SerializedName("FRA")
    Fra("FRA"),

    @SerializedName("FRO")
    Fro("FRO"),

    @SerializedName("FSM")
    Fsm("FSM"),

    @SerializedName("GAB")
    Gab("GAB"),

    @SerializedName("GBR")
    Gbr("GBR"),

    @SerializedName("GEO")
    Geo("GEO"),

    @SerializedName("GGY")
    Ggy("GGY"),

    @SerializedName("GHA")
    Gha("GHA"),

    @SerializedName("GIB")
    Gib("GIB"),

    @SerializedName("GIN")
    Gin("GIN"),

    @SerializedName("GLP")
    Glp("GLP"),

    @SerializedName("GMB")
    Gmb("GMB"),

    @SerializedName("GNB")
    Gnb("GNB"),

    @SerializedName("GNQ")
    Gnq("GNQ"),

    @SerializedName("GRC")
    Grc("GRC"),

    @SerializedName("GRD")
    Grd("GRD"),

    @SerializedName("GRL")
    Grl("GRL"),

    @SerializedName("GTM")
    Gtm("GTM"),

    @SerializedName("GUF")
    Guf("GUF"),

    @SerializedName("GUM")
    Gum("GUM"),

    @SerializedName("GUY")
    Guy("GUY"),

    @SerializedName("HKG")
    Hkg("HKG"),

    @SerializedName("HMD")
    Hmd("HMD"),

    @SerializedName("HND")
    Hnd("HND"),

    @SerializedName("HRV")
    Hrv("HRV"),

    @SerializedName("HTI")
    Hti("HTI"),

    @SerializedName("HUN")
    Hun("HUN"),

    @SerializedName("IDN")
    Idn("IDN"),

    @SerializedName("IMN")
    Imn("IMN"),

    @SerializedName("IND")
    Ind("IND"),

    @SerializedName("IOT")
    Iot("IOT"),

    @SerializedName("IRL")
    Irl("IRL"),

    @SerializedName("IRN")
    Irn("IRN"),

    @SerializedName("IRQ")
    Irq("IRQ"),

    @SerializedName("ISL")
    Isl("ISL"),

    @SerializedName("ISR")
    Isr("ISR"),

    @SerializedName("ITA")
    Ita("ITA"),

    @SerializedName("JAM")
    Jam("JAM"),

    @SerializedName("JEY")
    Jey("JEY"),

    @SerializedName("JOR")
    Jor("JOR"),

    @SerializedName("JPN")
    Jpn("JPN"),

    @SerializedName("KAZ")
    Kaz("KAZ"),

    @SerializedName("KEN")
    Ken("KEN"),

    @SerializedName("KGZ")
    Kgz("KGZ"),

    @SerializedName("KHM")
    Khm("KHM"),

    @SerializedName("KIR")
    Kir("KIR"),

    @SerializedName("KNA")
    Kna("KNA"),

    @SerializedName("KOR")
    Kor("KOR"),

    @SerializedName("KWT")
    Kwt("KWT"),

    @SerializedName("LAO")
    Lao("LAO"),

    @SerializedName("LBN")
    Lbn("LBN"),

    @SerializedName("LBR")
    Lbr("LBR"),

    @SerializedName("LBY")
    Lby("LBY"),

    @SerializedName("LCA")
    Lca("LCA"),

    @SerializedName("LIE")
    Lie("LIE"),

    @SerializedName("LKA")
    Lka("LKA"),

    @SerializedName("LSO")
    Lso("LSO"),

    @SerializedName("LTU")
    Ltu("LTU"),

    @SerializedName("LUX")
    Lux("LUX"),

    @SerializedName("LVA")
    Lva("LVA"),

    @SerializedName("MAC")
    Mac("MAC"),

    @SerializedName("MAF")
    Maf("MAF"),

    @SerializedName("MAR")
    Mar("MAR"),

    @SerializedName("MCO")
    Mco("MCO"),

    @SerializedName("MDA")
    Mda("MDA"),

    @SerializedName("MDG")
    Mdg("MDG"),

    @SerializedName("MDV")
    Mdv("MDV"),

    @SerializedName("MEX")
    Mex("MEX"),

    @SerializedName("MHL")
    Mhl("MHL"),

    @SerializedName("MKD")
    Mkd("MKD"),

    @SerializedName("MLI")
    Mli("MLI"),

    @SerializedName("MLT")
    Mlt("MLT"),

    @SerializedName("MMR")
    Mmr("MMR"),

    @SerializedName("MNE")
    Mne("MNE"),

    @SerializedName("MNG")
    Mng("MNG"),

    @SerializedName("MNP")
    Mnp("MNP"),

    @SerializedName("MOZ")
    Moz("MOZ"),

    @SerializedName("MRT")
    Mrt("MRT"),

    @SerializedName("MSR")
    Msr("MSR"),

    @SerializedName("MTQ")
    Mtq("MTQ"),

    @SerializedName("MUS")
    Mus("MUS"),

    @SerializedName("MWI")
    Mwi("MWI"),

    @SerializedName("MYS")
    Mys("MYS"),

    @SerializedName("MYT")
    Myt("MYT"),

    @SerializedName("NAM")
    Nam("NAM"),

    @SerializedName("NCL")
    Ncl("NCL"),

    @SerializedName("NER")
    Ner("NER"),

    @SerializedName("NFK")
    Nfk("NFK"),

    @SerializedName("NGA")
    Nga("NGA"),

    @SerializedName("NIC")
    Nic("NIC"),

    @SerializedName("NIU")
    Niu("NIU"),

    @SerializedName("NLD")
    Nld("NLD"),

    @SerializedName("NOR")
    Nor("NOR"),

    @SerializedName("NPL")
    Npl("NPL"),

    @SerializedName("NRU")
    Nru("NRU"),

    @SerializedName("NZL")
    Nzl("NZL"),

    @SerializedName("OMN")
    Omn("OMN"),

    @SerializedName("PAK")
    Pak("PAK"),

    @SerializedName("PAN")
    Pan("PAN"),

    @SerializedName("PCN")
    Pcn("PCN"),

    @SerializedName("PER")
    Per("PER"),

    @SerializedName("PHL")
    Phl("PHL"),

    @SerializedName("PLW")
    Plw("PLW"),

    @SerializedName("PNG")
    Png("PNG"),

    @SerializedName("POL")
    Pol("POL"),

    @SerializedName("PRI")
    Pri("PRI"),

    @SerializedName("PRK")
    Prk("PRK"),

    @SerializedName("PRT")
    Prt("PRT"),

    @SerializedName("PRY")
    Pry("PRY"),

    @SerializedName("PSE")
    Pse("PSE"),

    @SerializedName("PYF")
    Pyf("PYF"),

    @SerializedName("QAT")
    Qat("QAT"),

    @SerializedName("REU")
    Reu("REU"),

    @SerializedName("ROU")
    Rou("ROU"),

    @SerializedName("RUS")
    Rus("RUS"),

    @SerializedName("RWA")
    Rwa("RWA"),

    @SerializedName("SAU")
    Sau("SAU"),

    @SerializedName("SDN")
    Sdn("SDN"),

    @SerializedName("SEN")
    Sen("SEN"),

    @SerializedName("SGP")
    Sgp("SGP"),

    @SerializedName("SGS")
    Sgs("SGS"),

    @SerializedName("SHN")
    Shn("SHN"),

    @SerializedName("SJM")
    Sjm("SJM"),

    @SerializedName("SLB")
    Slb("SLB"),

    @SerializedName("SLE")
    Sle("SLE"),

    @SerializedName("SLV")
    Slv("SLV"),

    @SerializedName("SMR")
    Smr("SMR"),

    @SerializedName("SOM")
    Som("SOM"),

    @SerializedName("SPM")
    Spm("SPM"),

    @SerializedName("SRB")
    Srb("SRB"),

    @SerializedName("SSD")
    Ssd("SSD"),

    @SerializedName("STP")
    Stp("STP"),

    @SerializedName("SUR")
    Sur("SUR"),

    @SerializedName("SVK")
    Svk("SVK"),

    @SerializedName("SVN")
    Svn("SVN"),

    @SerializedName("SWE")
    Swe("SWE"),

    @SerializedName("SWZ")
    Swz("SWZ"),

    @SerializedName("SXM")
    Sxm("SXM"),

    @SerializedName("SYC")
    Syc("SYC"),

    @SerializedName("SYR")
    Syr("SYR"),

    @SerializedName("TCA")
    Tca("TCA"),

    @SerializedName("TCD")
    Tcd("TCD"),

    @SerializedName("TGO")
    Tgo("TGO"),

    @SerializedName("THA")
    Tha("THA"),

    @SerializedName("TJK")
    Tjk("TJK"),

    @SerializedName("TKL")
    Tkl("TKL"),

    @SerializedName("TKM")
    Tkm("TKM"),

    @SerializedName("TLS")
    Tls("TLS"),

    @SerializedName("TON")
    Ton("TON"),

    @SerializedName("TTO")
    Tto("TTO"),

    @SerializedName("TUN")
    Tun("TUN"),

    @SerializedName("TUR")
    Tur("TUR"),

    @SerializedName("TUV")
    Tuv("TUV"),

    @SerializedName("TWN")
    Twn("TWN"),

    @SerializedName("TZA")
    Tza("TZA"),

    @SerializedName("UGA")
    Uga("UGA"),

    @SerializedName("UKR")
    Ukr("UKR"),

    @SerializedName("UMI")
    Umi("UMI"),

    @SerializedName("UNK")
    Unk("UNK"),

    @SerializedName("URY")
    Ury("URY"),

    @SerializedName("USA")
    Usa("USA"),

    @SerializedName("UZB")
    Uzb("UZB"),

    @SerializedName("VAT")
    Vat("VAT"),

    @SerializedName("VCT")
    Vct("VCT"),

    @SerializedName("VEN")
    Ven("VEN"),

    @SerializedName("VGB")
    Vgb("VGB"),

    @SerializedName("VIR")
    Vir("VIR"),

    @SerializedName("VNM")
    Vnm("VNM"),

    @SerializedName("VUT")
    Vut("VUT"),

    @SerializedName("WLF")
    Wlf("WLF"),

    @SerializedName("WSM")
    Wsm("WSM"),

    @SerializedName("YEM")
    Yem("YEM"),

    @SerializedName("ZAF")
    Zaf("ZAF"),

    @SerializedName("ZMB")
    Zmb("ZMB"),

    @SerializedName("ZWE")
    Zwe("ZWE");

    private final String value;

    PaymentMethodAccountV3Country(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
