/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PickupV3 extends Resource {

    @SerializedName("id")
    private String id;

    @SerializedName("status")
    private PickupV3Status status;

    @SerializedName("pickup_confirmation_numbers")
    private java.util.List<String> pickupConfirmationNumbers;

    @SerializedName("pickup_location_code")
    private String pickupLocationCode;

    @SerializedName("pickup_date")
    private String pickupDate;

    @SerializedName("pickup_start_time")
    private String pickupStartTime;

    @SerializedName("pickup_end_time")
    private String pickupEndTime;

    @SerializedName("pickup_from")
    private AddressV3 pickupFrom;

    @SerializedName("ship_to")
    private AddressV3 shipTo;

    @SerializedName("label_ids")
    private java.util.List<String> labelIds;

    @SerializedName("pickup_parcels")
    private java.util.List<PickupParcelV3> pickupParcels;

    @SerializedName("shipper_account")
    private ReferenceV3 shipperAccount;

    @SerializedName("created_at")
    private String createdAt;

    @SerializedName("updated_at")
    private String updatedAt;

    public  String getId() {
        return id;
    }

    public void setId( String id) {
        this.id = id;
    }

    public  PickupV3Status getStatus() {
        return status;
    }

    public void setStatus( PickupV3Status status) {
        this.status = status;
    }

    public java.util.List<String>  getPickupConfirmationNumbers() {
        return pickupConfirmationNumbers;
    }

    public void setPickupConfirmationNumbers(java.util.List<String>  pickupConfirmationNumbers) {
        this.pickupConfirmationNumbers = pickupConfirmationNumbers;
    }

    public  String getPickupLocationCode() {
        return pickupLocationCode;
    }

    public void setPickupLocationCode( String pickupLocationCode) {
        this.pickupLocationCode = pickupLocationCode;
    }

    public  String getPickupDate() {
        return pickupDate;
    }

    public void setPickupDate( String pickupDate) {
        this.pickupDate = pickupDate;
    }

    public  String getPickupStartTime() {
        return pickupStartTime;
    }

    public void setPickupStartTime( String pickupStartTime) {
        this.pickupStartTime = pickupStartTime;
    }

    public  String getPickupEndTime() {
        return pickupEndTime;
    }

    public void setPickupEndTime( String pickupEndTime) {
        this.pickupEndTime = pickupEndTime;
    }

    public  AddressV3 getPickupFrom() {
        return pickupFrom;
    }

    public void setPickupFrom( AddressV3 pickupFrom) {
        this.pickupFrom = pickupFrom;
    }

    public  AddressV3 getShipTo() {
        return shipTo;
    }

    public void setShipTo( AddressV3 shipTo) {
        this.shipTo = shipTo;
    }

    public java.util.List<String>  getLabelIds() {
        return labelIds;
    }

    public void setLabelIds(java.util.List<String>  labelIds) {
        this.labelIds = labelIds;
    }

    public java.util.List<PickupParcelV3>  getPickupParcels() {
        return pickupParcels;
    }

    public void setPickupParcels(java.util.List<PickupParcelV3>  pickupParcels) {
        this.pickupParcels = pickupParcels;
    }

    public  ReferenceV3 getShipperAccount() {
        return shipperAccount;
    }

    public void setShipperAccount( ReferenceV3 shipperAccount) {
        this.shipperAccount = shipperAccount;
    }

    public  String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt( String createdAt) {
        this.createdAt = createdAt;
    }

    public  String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt( String updatedAt) {
        this.updatedAt = updatedAt;
    }

}
