/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum PostCancelLabelsResponseDataStatus {
    @SerializedName("cancelling")
    Cancelling("cancelling"),

    @SerializedName("cancelled")
    Cancelled("cancelled"),

    @SerializedName("failed")
    Failed("failed");

    private final String value;

    PostCancelLabelsResponseDataStatus(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
