/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostShipperAccountsRequest extends Resource {

    @SerializedName("slug")
    private String slug;

    @SerializedName("description")
    private String description;

    @SerializedName("timezone")
    private String timezone;

    @SerializedName("credentials")
    private Object credentials;

    @SerializedName("address")
    private AddressV3 address;

    @SerializedName("settings")
    private PostShipperAccountsRequestSettings settings;

    public  String getSlug() {
        return slug;
    }

    public void setSlug( String slug) {
        this.slug = slug;
    }

    public  String getDescription() {
        return description;
    }

    public void setDescription( String description) {
        this.description = description;
    }

    public  String getTimezone() {
        return timezone;
    }

    public void setTimezone( String timezone) {
        this.timezone = timezone;
    }

    public  Object getCredentials() {
        return credentials;
    }

    public void setCredentials( Object credentials) {
        this.credentials = credentials;
    }

    public  AddressV3 getAddress() {
        return address;
    }

    public void setAddress( AddressV3 address) {
        this.address = address;
    }

    public  PostShipperAccountsRequestSettings getSettings() {
        return settings;
    }

    public void setSettings( PostShipperAccountsRequestSettings settings) {
        this.settings = settings;
    }

}
