/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostAddressValidationsRequest extends Resource {

    @SerializedName("address")
    private AddressV3 address;

    public  AddressV3 getAddress() {
        return address;
    }

    public void setAddress( AddressV3 address) {
        this.address = address;
    }

}
