/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostPickupsRequest extends Resource {

    @SerializedName("pickup_date")
    private String pickupDate;

    @SerializedName("pickup_start_time")
    private String pickupStartTime;

    @SerializedName("pickup_end_time")
    private String pickupEndTime;

    @SerializedName("pickup_from")
    private AddressV3 pickupFrom;

    @SerializedName("ship_to")
    private AddressV3 shipTo;

    @SerializedName("label_ids")
    private java.util.List<String> labelIds;

    @SerializedName("pickup_parcels")
    private java.util.List<PickupParcelV3> pickupParcels;

    @SerializedName("shipper_account")
    private ReferenceV3 shipperAccount;

    @SerializedName("pickup_location")
    private String pickupLocation;

    @SerializedName("pickup_instructions")
    private String pickupInstructions;

    public  String getPickupDate() {
        return pickupDate;
    }

    public void setPickupDate( String pickupDate) {
        this.pickupDate = pickupDate;
    }

    public  String getPickupStartTime() {
        return pickupStartTime;
    }

    public void setPickupStartTime( String pickupStartTime) {
        this.pickupStartTime = pickupStartTime;
    }

    public  String getPickupEndTime() {
        return pickupEndTime;
    }

    public void setPickupEndTime( String pickupEndTime) {
        this.pickupEndTime = pickupEndTime;
    }

    public  AddressV3 getPickupFrom() {
        return pickupFrom;
    }

    public void setPickupFrom( AddressV3 pickupFrom) {
        this.pickupFrom = pickupFrom;
    }

    public  AddressV3 getShipTo() {
        return shipTo;
    }

    public void setShipTo( AddressV3 shipTo) {
        this.shipTo = shipTo;
    }

    public java.util.List<String>  getLabelIds() {
        return labelIds;
    }

    public void setLabelIds(java.util.List<String>  labelIds) {
        this.labelIds = labelIds;
    }

    public java.util.List<PickupParcelV3>  getPickupParcels() {
        return pickupParcels;
    }

    public void setPickupParcels(java.util.List<PickupParcelV3>  pickupParcels) {
        this.pickupParcels = pickupParcels;
    }

    public  ReferenceV3 getShipperAccount() {
        return shipperAccount;
    }

    public void setShipperAccount( ReferenceV3 shipperAccount) {
        this.shipperAccount = shipperAccount;
    }

    public  String getPickupLocation() {
        return pickupLocation;
    }

    public void setPickupLocation( String pickupLocation) {
        this.pickupLocation = pickupLocation;
    }

    public  String getPickupInstructions() {
        return pickupInstructions;
    }

    public void setPickupInstructions( String pickupInstructions) {
        this.pickupInstructions = pickupInstructions;
    }

}
