/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum PostLabelsRequestFileType {
    @SerializedName("pdf")
    Pdf("pdf"),

    @SerializedName("zpl")
    Zpl("zpl");

    private final String value;

    PostLabelsRequestFileType(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
