/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostLabelsRequest extends Resource {

    @SerializedName("billing")
    private BillingV3 billing;

    @SerializedName("customs")
    private CustomsV3 customs;

    @SerializedName("return_shipment")
    private Boolean returnShipment;

    @SerializedName("is_document")
    private Boolean isDocument;

    @SerializedName("service_type")
    private String serviceType;

    @SerializedName("paper_size")
    private String paperSize;

    @SerializedName("shipper_account")
    private PostLabelsRequestShipperAccount shipperAccount;

    @SerializedName("references")
    private java.util.List<String> references;

    @SerializedName("shipment")
    private ShipmentV3 shipment;

    @SerializedName("invoice")
    private InvoiceV3 invoice;

    @SerializedName("service_options")
    private java.util.List<Object> serviceOptions;

    @SerializedName("file_type")
    private PostLabelsRequestFileType fileType;

    @SerializedName("ship_date")
    private String shipDate;

    @SerializedName("order_number")
    private String orderNumber;

    @SerializedName("order_id")
    private String orderId;

    @SerializedName("custom_fields")
    private java.util.Map<String,String> customFields;

    @SerializedName("files")
    private InputFilesV3 files;

    @SerializedName("print_options")
    private PostLabelsRequestPrintOptions printOptions;

    public  BillingV3 getBilling() {
        return billing;
    }

    public void setBilling( BillingV3 billing) {
        this.billing = billing;
    }

    public  CustomsV3 getCustoms() {
        return customs;
    }

    public void setCustoms( CustomsV3 customs) {
        this.customs = customs;
    }

    public  Boolean getReturnShipment() {
        return returnShipment;
    }

    public void setReturnShipment( Boolean returnShipment) {
        this.returnShipment = returnShipment;
    }

    public  Boolean getIsDocument() {
        return isDocument;
    }

    public void setIsDocument( Boolean isDocument) {
        this.isDocument = isDocument;
    }

    public  String getServiceType() {
        return serviceType;
    }

    public void setServiceType( String serviceType) {
        this.serviceType = serviceType;
    }

    public  String getPaperSize() {
        return paperSize;
    }

    public void setPaperSize( String paperSize) {
        this.paperSize = paperSize;
    }

    public  PostLabelsRequestShipperAccount getShipperAccount() {
        return shipperAccount;
    }

    public void setShipperAccount( PostLabelsRequestShipperAccount shipperAccount) {
        this.shipperAccount = shipperAccount;
    }

    public java.util.List<String>  getReferences() {
        return references;
    }

    public void setReferences(java.util.List<String>  references) {
        this.references = references;
    }

    public  ShipmentV3 getShipment() {
        return shipment;
    }

    public void setShipment( ShipmentV3 shipment) {
        this.shipment = shipment;
    }

    public  InvoiceV3 getInvoice() {
        return invoice;
    }

    public void setInvoice( InvoiceV3 invoice) {
        this.invoice = invoice;
    }

    public java.util.List<Object>  getServiceOptions() {
        return serviceOptions;
    }

    public void setServiceOptions(java.util.List<Object>  serviceOptions) {
        this.serviceOptions = serviceOptions;
    }

    public  PostLabelsRequestFileType getFileType() {
        return fileType;
    }

    public void setFileType( PostLabelsRequestFileType fileType) {
        this.fileType = fileType;
    }

    public  String getShipDate() {
        return shipDate;
    }

    public void setShipDate( String shipDate) {
        this.shipDate = shipDate;
    }

    public  String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber( String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public  String getOrderId() {
        return orderId;
    }

    public void setOrderId( String orderId) {
        this.orderId = orderId;
    }

    public  java.util.Map<String,String> getCustomFields() {
        return customFields;
    }

    public void setCustomFields( java.util.Map<String,String> customFields) {
        this.customFields = customFields;
    }

    public  InputFilesV3 getFiles() {
        return files;
    }

    public void setFiles( InputFilesV3 files) {
        this.files = files;
    }

    public  PostLabelsRequestPrintOptions getPrintOptions() {
        return printOptions;
    }

    public void setPrintOptions( PostLabelsRequestPrintOptions printOptions) {
        this.printOptions = printOptions;
    }

}
