/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostLabelsRequestPrintOptions extends Resource {

    @SerializedName("qr_code")
    private PostLabelsRequestPrintOptionsQrCode qrCode;

    public  PostLabelsRequestPrintOptionsQrCode getQrCode() {
        return qrCode;
    }

    public void setQrCode( PostLabelsRequestPrintOptionsQrCode qrCode) {
        this.qrCode = qrCode;
    }

}
