/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostCancelPickupsResponseData extends Resource {

    @SerializedName("id")
    private String id;

    @SerializedName("status")
    private PostCancelPickupsResponseDataStatus status;

    @SerializedName("pickup")
    private PostCancelPickupsResponseDataPickup pickup;

    @SerializedName("created_at")
    private String createdAt;

    @SerializedName("updated_at")
    private String updatedAt;

    public  String getId() {
        return id;
    }

    public void setId( String id) {
        this.id = id;
    }

    public  PostCancelPickupsResponseDataStatus getStatus() {
        return status;
    }

    public void setStatus( PostCancelPickupsResponseDataStatus status) {
        this.status = status;
    }

    public  PostCancelPickupsResponseDataPickup getPickup() {
        return pickup;
    }

    public void setPickup( PostCancelPickupsResponseDataPickup pickup) {
        this.pickup = pickup;
    }

    public  String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt( String createdAt) {
        this.createdAt = createdAt;
    }

    public  String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt( String updatedAt) {
        this.updatedAt = updatedAt;
    }

}
