/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostRatesRequest extends Resource {

    @SerializedName("async")
    private Boolean async;

    @SerializedName("is_document")
    private Boolean isDocument;

    @SerializedName("ship_date")
    private String shipDate;

    @SerializedName("shipper_accounts")
    private java.util.List<PostRatesRequestShipperAccounts> shipperAccounts;

    @SerializedName("shipment")
    private ShipmentV3 shipment;

    @SerializedName("expected_delivery_date")
    private String expectedDeliveryDate;

    public  Boolean getAsync() {
        return async;
    }

    public void setAsync( Boolean async) {
        this.async = async;
    }

    public  Boolean getIsDocument() {
        return isDocument;
    }

    public void setIsDocument( Boolean isDocument) {
        this.isDocument = isDocument;
    }

    public  String getShipDate() {
        return shipDate;
    }

    public void setShipDate( String shipDate) {
        this.shipDate = shipDate;
    }

    public java.util.List<PostRatesRequestShipperAccounts>  getShipperAccounts() {
        return shipperAccounts;
    }

    public void setShipperAccounts(java.util.List<PostRatesRequestShipperAccounts>  shipperAccounts) {
        this.shipperAccounts = shipperAccounts;
    }

    public  ShipmentV3 getShipment() {
        return shipment;
    }

    public void setShipment( ShipmentV3 shipment) {
        this.shipment = shipment;
    }

    public  String getExpectedDeliveryDate() {
        return expectedDeliveryDate;
    }

    public void setExpectedDeliveryDate( String expectedDeliveryDate) {
        this.expectedDeliveryDate = expectedDeliveryDate;
    }

}
