/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostLabelsRequestPrintOptionsQrCode extends Resource {

    @SerializedName("enabled")
    private Boolean enabled;

    public  Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled( Boolean enabled) {
        this.enabled = enabled;
    }

}
