/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostCancelLabelsRequest extends Resource {

    @SerializedName("label")
    private PostCancelLabelsRequestLabel label;

    public  PostCancelLabelsRequestLabel getLabel() {
        return label;
    }

    public void setLabel( PostCancelLabelsRequestLabel label) {
        this.label = label;
    }

}
