/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostCancelPickupsRequest extends Resource {

    @SerializedName("pickup")
    private PostCancelPickupsRequestPickup pickup;

    public  PostCancelPickupsRequestPickup getPickup() {
        return pickup;
    }

    public void setPickup( PostCancelPickupsRequestPickup pickup) {
        this.pickup = pickup;
    }

}
