/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PostShipperAccountsRequestSettings extends Resource {

    @SerializedName("commercial_invoice_letterhead")
    private String commercialInvoiceLetterhead;

    @SerializedName("commercial_invoice_signature")
    private String commercialInvoiceSignature;

    public  String getCommercialInvoiceLetterhead() {
        return commercialInvoiceLetterhead;
    }

    public void setCommercialInvoiceLetterhead( String commercialInvoiceLetterhead) {
        this.commercialInvoiceLetterhead = commercialInvoiceLetterhead;
    }

    public  String getCommercialInvoiceSignature() {
        return commercialInvoiceSignature;
    }

    public void setCommercialInvoiceSignature( String commercialInvoiceSignature) {
        this.commercialInvoiceSignature = commercialInvoiceSignature;
    }

}
