/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class PutShipperAccountsIdInfoRequest extends Resource {

    @SerializedName("description")
    private String description;

    @SerializedName("timezone")
    private String timezone;

    @SerializedName("address")
    private AddressV3 address;

    public  String getDescription() {
        return description;
    }

    public void setDescription( String description) {
        this.description = description;
    }

    public  String getTimezone() {
        return timezone;
    }

    public void setTimezone( String timezone) {
        this.timezone = timezone;
    }

    public  AddressV3 getAddress() {
        return address;
    }

    public void setAddress( AddressV3 address) {
        this.address = address;
    }

}
