/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class RateV3DetailedCharges extends Resource {

    @SerializedName("type")
    private String type;

    @SerializedName("charge")
    private MoneyV3 charge;

    public  String getType() {
        return type;
    }

    public void setType( String type) {
        this.type = type;
    }

    public  MoneyV3 getCharge() {
        return charge;
    }

    public void setCharge( MoneyV3 charge) {
        this.charge = charge;
    }

}
