/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum RateRecordV3Status {
    @SerializedName("calculating")
    Calculating("calculating"),

    @SerializedName("calculated")
    Calculated("calculated"),

    @SerializedName("failed")
    Failed("failed");

    private final String value;

    RateRecordV3Status(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
