/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class ReferenceV3 extends Resource {

    @SerializedName("id")
    private String id;

    public  String getId() {
        return id;
    }

    public void setId( String id) {
        this.id = id;
    }

}
