/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class ShipperAccountV3 extends Resource {

    @SerializedName("id")
    private String id;

    @SerializedName("address")
    private AddressV3 address;

    @SerializedName("slug")
    private String slug;

    @SerializedName("status")
    private ShipperAccountV3Status status;

    @SerializedName("description")
    private String description;

    @SerializedName("type")
    private ShipperAccountV3Type type;

    @SerializedName("timezone")
    private String timezone;

    @SerializedName("settings")
    private ShipperAccountV3Settings settings;

    @SerializedName("created_at")
    private String createdAt;

    @SerializedName("updated_at")
    private String updatedAt;

    public  String getId() {
        return id;
    }

    public void setId( String id) {
        this.id = id;
    }

    public  AddressV3 getAddress() {
        return address;
    }

    public void setAddress( AddressV3 address) {
        this.address = address;
    }

    public  String getSlug() {
        return slug;
    }

    public void setSlug( String slug) {
        this.slug = slug;
    }

    public  ShipperAccountV3Status getStatus() {
        return status;
    }

    public void setStatus( ShipperAccountV3Status status) {
        this.status = status;
    }

    public  String getDescription() {
        return description;
    }

    public void setDescription( String description) {
        this.description = description;
    }

    public  ShipperAccountV3Type getType() {
        return type;
    }

    public void setType( ShipperAccountV3Type type) {
        this.type = type;
    }

    public  String getTimezone() {
        return timezone;
    }

    public void setTimezone( String timezone) {
        this.timezone = timezone;
    }

    public  ShipperAccountV3Settings getSettings() {
        return settings;
    }

    public void setSettings( ShipperAccountV3Settings settings) {
        this.settings = settings;
    }

    public  String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt( String createdAt) {
        this.createdAt = createdAt;
    }

    public  String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt( String updatedAt) {
        this.updatedAt = updatedAt;
    }

}
