/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;

public enum ShipperAccountV3Status {
    @SerializedName("enabled")
    Enabled("enabled"),

    @SerializedName("disabled")
    Disabled("disabled"),

    @SerializedName("deleted")
    Deleted("deleted");

    private final String value;

    ShipperAccountV3Status(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
