/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.shipping.base.Resource;

public class WeightV3 extends Resource {

    @SerializedName("unit")
    private WeightV3Unit unit;

    @SerializedName("value")
    private Float value;

    public  WeightV3Unit getUnit() {
        return unit;
    }

    public void setUnit( WeightV3Unit unit) {
        this.unit = unit;
    }

    public  Float getValue() {
        return value;
    }

    public void setValue( Float value) {
        this.value = value;
    }

}
