/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.couriers;

import com.aftership.shipping.base.Resource;

public class CouriersResource extends Resource {
    public static GetCouriersFetcher getCouriers() {
        return new GetCouriersFetcher();
    }
}
