/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.couriers;

import com.aftership.shipping.base.Fetcher;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.GetCouriersResponse;
import com.aftership.shipping.model.GetCouriersResponseData;

public class GetCouriersFetcher extends Fetcher<GetCouriersResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public GetCouriersFetcher addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }

    @Override
    public GetCouriersResponse fetch(AfterShipClient client) throws Exception {
        String path = "/postmen/v3/couriers";
        Request request = new Request(HttpMethod.GET, path);
        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<GetCouriersResponseData> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<GetCouriersResponseData>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        GetCouriersResponse result = new GetCouriersResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
