/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.pickups;

import com.aftership.shipping.base.Fetcher;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.GetPickupsResponse;
import com.aftership.shipping.model.GetPickupsResponseData;

public class GetPickupsFetcher extends Fetcher<GetPickupsResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public GetPickupsFetcher addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
     private String status;

     private String limit;

     private String createdAtMin;

     private String createdAtMax;

     private String nextToken;


    public GetPickupsFetcher setStatus(String status) {
        this.status = status;
        return this;
    }

    public GetPickupsFetcher setLimit(String limit) {
        this.limit = limit;
        return this;
    }

    public GetPickupsFetcher setCreatedAtMin(String createdAtMin) {
        this.createdAtMin = createdAtMin;
        return this;
    }

    public GetPickupsFetcher setCreatedAtMax(String createdAtMax) {
        this.createdAtMax = createdAtMax;
        return this;
    }

    public GetPickupsFetcher setNextToken(String nextToken) {
        this.nextToken = nextToken;
        return this;
    }

    @Override
    public GetPickupsResponse fetch(AfterShipClient client) throws Exception {
        String path = "/postmen/v3/pickups";
        Request request = new Request(HttpMethod.GET, path);
        addQueryParams(request);
        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<GetPickupsResponseData> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<GetPickupsResponseData>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        GetPickupsResponse result = new GetPickupsResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

    private void addQueryParams(final Request request) {
        if (status != null) {
            request.addQueryParam("status", status);
        }
        if (limit != null) {
            request.addQueryParam("limit", limit);
        }
        if (createdAtMin != null) {
            request.addQueryParam("created_at_min", createdAtMin);
        }
        if (createdAtMax != null) {
            request.addQueryParam("created_at_max", createdAtMax);
        }
        if (nextToken != null) {
            request.addQueryParam("next_token", nextToken);
        }
    }
}
