/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.shipper_accounts;

import com.aftership.shipping.base.Fetcher;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.GetShipperAccountsResponse;
import com.aftership.shipping.model.GetShipperAccountsResponseData;

public class GetShipperAccountsFetcher extends Fetcher<GetShipperAccountsResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public GetShipperAccountsFetcher addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
     private String slug;

     private String limit;

     private String nextToken;


    public GetShipperAccountsFetcher setSlug(String slug) {
        this.slug = slug;
        return this;
    }

    public GetShipperAccountsFetcher setLimit(String limit) {
        this.limit = limit;
        return this;
    }

    public GetShipperAccountsFetcher setNextToken(String nextToken) {
        this.nextToken = nextToken;
        return this;
    }

    @Override
    public GetShipperAccountsResponse fetch(AfterShipClient client) throws Exception {
        String path = "/postmen/v3/shipper-accounts";
        Request request = new Request(HttpMethod.GET, path);
        addQueryParams(request);
        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<GetShipperAccountsResponseData> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<GetShipperAccountsResponseData>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        GetShipperAccountsResponse result = new GetShipperAccountsResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

    private void addQueryParams(final Request request) {
        if (slug != null) {
            request.addQueryParam("slug", slug);
        }
        if (limit != null) {
            request.addQueryParam("limit", limit);
        }
        if (nextToken != null) {
            request.addQueryParam("next_token", nextToken);
        }
    }
}
