/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.shipper_accounts;

import com.aftership.shipping.base.Updater;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.PatchShipperAccountsIdSettingsResponse;
import com.aftership.shipping.model.PatchShipperAccountsIdSettingsResponseData;
import com.aftership.shipping.model.PatchShipperAccountsIdSettingsRequest;

public class PatchShipperAccountsIdSettingsUpdater extends Updater<PatchShipperAccountsIdSettingsResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public PatchShipperAccountsIdSettingsUpdater addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private PatchShipperAccountsIdSettingsRequest patchShipperAccountsIdSettingsRequest;

    public PatchShipperAccountsIdSettingsUpdater setPatchShipperAccountsIdSettingsRequest(PatchShipperAccountsIdSettingsRequest patchShipperAccountsIdSettingsRequest) {
        this.patchShipperAccountsIdSettingsRequest = patchShipperAccountsIdSettingsRequest;
        return this;
    }
    private String id;


    public PatchShipperAccountsIdSettingsUpdater setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public PatchShipperAccountsIdSettingsResponse update(AfterShipClient client) throws Exception {
        if (id == null || id.isEmpty()) {
            throw new ApiException(ErrorEnum.BAD_REQUEST.name(), "Invalid request: `id` is invalid");
        }
        String path = String.format("/postmen/v3/shipper-accounts/%s/settings", id);
        Request request = new Request(HttpMethod.PATCH, path);
        request.setBody((new Gson()).toJson(patchShipperAccountsIdSettingsRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<PatchShipperAccountsIdSettingsResponseData> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<PatchShipperAccountsIdSettingsResponseData>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        PatchShipperAccountsIdSettingsResponse result = new PatchShipperAccountsIdSettingsResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
