/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.shipper_accounts;

import com.aftership.shipping.base.Creator;
import com.aftership.shipping.constant.ErrorEnum;
import com.aftership.shipping.exception.ApiException;
import com.aftership.shipping.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.shipping.http.Request;
import com.aftership.shipping.model.PostShipperAccountsResponse;
import com.aftership.shipping.model.ShipperAccountV3;
import com.aftership.shipping.model.PostShipperAccountsRequest;

public class PostShipperAccountsCreator extends Creator<PostShipperAccountsResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public PostShipperAccountsCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private PostShipperAccountsRequest postShipperAccountsRequest;

    public PostShipperAccountsCreator setPostShipperAccountsRequest(PostShipperAccountsRequest postShipperAccountsRequest) {
        this.postShipperAccountsRequest = postShipperAccountsRequest;
        return this;
    }

    @Override
    public PostShipperAccountsResponse create(AfterShipClient client) throws Exception {
        String path = "/postmen/v3/shipper-accounts";
        Request request = new Request(HttpMethod.POST, path);
        request.setBody((new Gson()).toJson(postShipperAccountsRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<ShipperAccountV3> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<ShipperAccountV3>>() {
            }.getType());
        if (responseData.getMeta() != null && responseData.getMeta().getCode() > 299) {
            throw new ApiException(
                    responseData.getMeta().getCode(),
                    responseData.getMeta().getMessage(),
                    ErrorEnum.getCode(response.getStatusCode(), responseData.getMeta().getCode()),
                    response.getStatusCode(),
                    response.getContent(),
                    response.getHeaders()
            );
        }
        PostShipperAccountsResponse result = new PostShipperAccountsResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
