/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.base;

import com.aftership.shipping.http.AfterShipClient;
import com.aftership.shipping.ShippingSdk;

public abstract class Deleter<T extends Resource> {

    public T delete() throws Exception {
        return delete(ShippingSdk.getRestClient());
    }

    public abstract T delete(final AfterShipClient client) throws Exception;
}
