/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.base;

import java.io.Serializable;

public abstract class Resource implements Serializable {

    private static final long serialVersionUID = -3063712988312126015L;
}
