/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.shipping.base;

import com.aftership.shipping.http.AfterShipClient;
import com.aftership.shipping.ShippingSdk;

public abstract class Updater<T extends Resource> {

    public T update() throws Exception {
        return update(ShippingSdk.getRestClient());
    }

    public abstract T update(final AfterShipClient client) throws Exception;
}
